# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: "Run docker as the build environment"
description: "Run commands in the given docker image with the build environment setup"

inputs:
  image:
    description: "Docker image to use"
    required: false
    default: "rapidstream/tapa-buildenv:local"
  run:
    description: "Command to run in the docker container"
    required: true
  dockerOptions:
    description: "Additional options to pass to the docker run command"
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure the build cache directories are present and owned by the current user
      run: |
        mkdir -p ~/.cache/rapidstream-tapa-cache
        mkdir -p ~/.cache/rapidstream-tapa-local
      shell: bash

    - name: Run commands in the Docker container with the build environment setup
      run: |
        # TODO: remove once all runners are labeled.
        containers=($(docker ps --filter=health=none --format={{.ID}}))
        if (( ${#containers[@]} )); then
          docker stop "${containers[@]}"
        fi
        label=tapa-github-runner
        containers=($(docker ps --filter=label="${label}" --format={{.ID}}))
        if (( ${#containers[@]} )); then
          docker stop "${containers[@]}"
        fi
        docker run \
          --rm \
          --init \
          --label="${label}" \
          --mac-address=${{ env.MAC_ADDRESS }} \
          -v /share/software/licenses:/opt/licenses:ro \
          -v /share/software/tools:/opt/tools:ro \
          -v /share/software/xilinx/platforms:/opt/xilinx/platforms:ro \
          -v ${{ github.workspace }}:/workspace \
          -v ~/.cache/rapidstream-tapa-cache:/tmp/home/.cache \
          -v ~/.cache/rapidstream-tapa-local:/tmp/home/.local \
          -v ${GITHUB_STEP_SUMMARY}:/workspace/.github_step_summary \
          -w /workspace \
          -e GITHUB_ACTIONS=true \
          -e GITHUB_STEP_SUMMARY=/workspace/.github_step_summary \
          -e LM_LICENSE_FILE=/opt/licenses/xilinx-ci.lic \
          -e VIVADO_IMPL_JOBS=1 \
          -e VIVADO_SYNTH_JOBS=1 \
          -e VIVADO_MAX_THREADS=1 \
          -e USER="$(id -u)" \
          -u $(id -u):$(id -g) \
          ${{ inputs.dockerOptions }} \
          --entrypoint=/bin/bash \
          ${{ inputs.image }} \
          -c " \
            set -xe
            ${{ inputs.run }}
          "
      shell: bash
