# syntax = edrevo/dockerfile-plus

# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

FROM debian:bullseye-20250407

INCLUDE+ Dockerfile.debian-common
