# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

ARG DOCKER_USER_ID
ARG DOCKER_GROUP_ID

# Testing framework:
#   - bats (from source)
#   - parallel

# Required by Vivado:
#   - gcc-multilib
#   - libtinfo5
#   - libx11-6
#   - locales

# Required by us:
#   - g++
#   - ocl-icd-libopencl1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
      # Update the following line to the latest date for retriggering the docker build
      echo "Installing system dependencies as of 20250325" && \
      apt-get upgrade -y && \
      apt-get install --no-install-recommends -y \
        ca-certificates \
        g++ \
        gcc-multilib \
        git \
        libtinfo5 \
        libx11-6 \
        locales \
        ocl-icd-libopencl1 \
        parallel \
      && \
      git clone https://github.com/bats-core/bats-core.git /tmp/bats-core && \
      cd /tmp/bats-core && \
      ./install.sh /usr/local && \
      apt-get purge -y --auto-remove \
        ca-certificates \
        git \
      && \
      rm -rf /var/lib/apt/lists/* && \
      rm -rf /var/cache/apt/* && \
      rm -rf /tmp/* /var/tmp/* && \
      true

# Regenerate the locales for Vivado
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

# Create a user for the test environment
RUN addgroup --uid ${DOCKER_GROUP_ID} io && \
    adduser --uid ${DOCKER_USER_ID} --ingroup io --home /tmp io

USER io
ENV HOME="/tmp"
WORKDIR /tmp
