# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

FROM ubuntu:bionic

ARG DOCKER_USER_ID
ARG DOCKER_GROUP_ID

# Testing framework:
#   - bats

# Required by Vivado:
#   - libtinfo5
#   - libx11-6
#   - locales

# Required by v++:
#   - unzip

# Required by us:
#   - g++
#   - iverilog
#   - ocl-icd-libopencl1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
      apt-get upgrade -y && \
      apt-get install --no-install-recommends -y \
        bats \
        ca-certificates \
        curl \
        g++ \
        iverilog \
        libtinfo5 \
        libx11-6 \
        locales \
        ocl-icd-libopencl1 \
        unzip \
      && \
      curl -fsSL https://www.xilinx.com/bin/public/openDownload?filename=xrt_202320.2.16.204_18.04-amd64-xrt.deb \
        -o /tmp/xrt.deb && \
      apt-get install -y /tmp/xrt.deb && \
      apt-get purge --auto-remove -y \
        ca-certificates \
        curl \
      && \
      rm -rf /var/lib/apt/lists/* && \
      rm -rf /var/cache/apt/* && \
      rm -rf /tmp/* /var/tmp/* && \
      true

# Regenerate the locales for Vivado
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

# Create a user for the test environment
RUN addgroup --uid ${DOCKER_GROUP_ID} io && \
    adduser --uid ${DOCKER_USER_ID} --ingroup io --home /tmp io

USER io
ENV HOME="/tmp"
WORKDIR /tmp
