# syntax = edrevo/dockerfile-plus

# Copyright (c) 2025 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

FROM ubuntu:jammy-20250404

INCLUDE+ Dockerfile.debian-common
