# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

ARG DOCKER_USER_ID
ARG DOCKER_GROUP_ID

# Testing framework:
#   - bats (from source)
#   - parallel
#   - perl
#   - util-linux

# Required by Vivado:
#   - hostname
#   - libX11

# Required by us:
#   - gcc-c++

RUN yum update -y && \
    # Update the following line to the latest date for retriggering the docker build
    echo "Installing system dependencies as of 20250505" && \
    yum install -y \
        gcc-c++ \
        git \
        glibc-langpack-en \
        hostname \
        libX11 \
        libxcrypt-compat \
        parallel \
        perl \
        util-linux \
    && \
    cd /tmp && \
      git clone https://github.com/bats-core/bats-core.git bats-core && \
      cd bats-core && \
      ./install.sh /usr/local && \
    yum remove -y git && \
    yum clean all && \
    rm -rf /tmp/* /var/tmp/* && \
    true

# Link libtinfo.so.6 to libtinfo.so.5 if it doesn't exist
RUN if [ ! -f /lib64/libtinfo.so.5 ]; then ln -s /lib64/libtinfo.so.6 /lib64/libtinfo.so.5; fi

# Create a user for the test environment
RUN groupadd -g ${DOCKER_GROUP_ID} io && \
    useradd -u ${DOCKER_USER_ID} -g io -d /tmp io

USER io
ENV HOME="/tmp"
WORKDIR /tmp
