# syntax = edrevo/dockerfile-plus

# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

FROM ubuntu:bionic

ARG XRT_VERSION=202320.2.16.204
ARG UBUNTU_VERSION=18.04

INCLUDE+ Dockerfile.ubuntu-common
