# syntax = edrevo/dockerfile-plus

# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

FROM almalinux:9.6-20250712

INCLUDE+ Dockerfile.rhel-common
