#!/bin/bash

# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

# set -e: Exit immediately if a command exits with a non-zero status
set -e

# Source the settings64.sh file to set up the Vitis HLS environment
source /opt/tools/xilinx/Vitis_HLS/2024.1/settings64.sh

# Dump the trash generated by Vitis HLS to /tmp
export HOME=/tmp

# Execute the command passed as arguments
exec "$@"
