#!/bin/bash
# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.
set -e

# Use the oldest supported version to ensure compatibility
source /opt/tools/xilinx/Vivado/2022.1/settings64.sh

# Dump the trash generated by Vivado to /tmp
export HOME=/tmp

# Execute the argument passed to xsc
exec xsc "$@"
