// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

(* CORE_GENERATION_INFO="SLOT_X0Y2_SLOT_X0Y2_SLOT_X0Y2_SLOT_X0Y2,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.215450,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=25,HLS_VERSION=2024_2}" *)
module SLOT_X0Y2_SLOT_X0Y2 (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        n,
        a_q_VecAdd_s_din,
        a_q_VecAdd_s_full_n,
        a_q_VecAdd_s_write,
        a_q_VecAdd_peek,
        mmap_Mmap2Stream_0
,
  m_axi_mmap_Mmap2Stream_0_ARADDR,
  m_axi_mmap_Mmap2Stream_0_ARBURST,
  m_axi_mmap_Mmap2Stream_0_ARCACHE,
  m_axi_mmap_Mmap2Stream_0_ARID,
  m_axi_mmap_Mmap2Stream_0_ARLEN,
  m_axi_mmap_Mmap2Stream_0_ARLOCK,
  m_axi_mmap_Mmap2Stream_0_ARPROT,
  m_axi_mmap_Mmap2Stream_0_ARQOS,
  m_axi_mmap_Mmap2Stream_0_ARREADY,
  m_axi_mmap_Mmap2Stream_0_ARSIZE,
  m_axi_mmap_Mmap2Stream_0_ARVALID,
  m_axi_mmap_Mmap2Stream_0_AWADDR,
  m_axi_mmap_Mmap2Stream_0_AWBURST,
  m_axi_mmap_Mmap2Stream_0_AWCACHE,
  m_axi_mmap_Mmap2Stream_0_AWID,
  m_axi_mmap_Mmap2Stream_0_AWLEN,
  m_axi_mmap_Mmap2Stream_0_AWLOCK,
  m_axi_mmap_Mmap2Stream_0_AWPROT,
  m_axi_mmap_Mmap2Stream_0_AWQOS,
  m_axi_mmap_Mmap2Stream_0_AWREADY,
  m_axi_mmap_Mmap2Stream_0_AWSIZE,
  m_axi_mmap_Mmap2Stream_0_AWVALID,
  m_axi_mmap_Mmap2Stream_0_BID,
  m_axi_mmap_Mmap2Stream_0_BREADY,
  m_axi_mmap_Mmap2Stream_0_BRESP,
  m_axi_mmap_Mmap2Stream_0_BVALID,
  m_axi_mmap_Mmap2Stream_0_RDATA,
  m_axi_mmap_Mmap2Stream_0_RID,
  m_axi_mmap_Mmap2Stream_0_RLAST,
  m_axi_mmap_Mmap2Stream_0_RREADY,
  m_axi_mmap_Mmap2Stream_0_RRESP,
  m_axi_mmap_Mmap2Stream_0_RVALID,
  m_axi_mmap_Mmap2Stream_0_WDATA,
  m_axi_mmap_Mmap2Stream_0_WLAST,
  m_axi_mmap_Mmap2Stream_0_WREADY,
  m_axi_mmap_Mmap2Stream_0_WSTRB,
  m_axi_mmap_Mmap2Stream_0_WVALID);
input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] a;
input  [63:0] n;
output  [32:0] a_q_VecAdd_s_din;
input   a_q_VecAdd_s_full_n;
output   a_q_VecAdd_s_write;
input  [32:0] a_q_VecAdd_peek;
input  [63:0] mmap_Mmap2Stream_0;
  output [63:0] m_axi_mmap_Mmap2Stream_0_ARADDR;
  output [1:0] m_axi_mmap_Mmap2Stream_0_ARBURST;
  output [3:0] m_axi_mmap_Mmap2Stream_0_ARCACHE;
  output [0:0] m_axi_mmap_Mmap2Stream_0_ARID;
  output [7:0] m_axi_mmap_Mmap2Stream_0_ARLEN;
  output m_axi_mmap_Mmap2Stream_0_ARLOCK;
  output [2:0] m_axi_mmap_Mmap2Stream_0_ARPROT;
  output [3:0] m_axi_mmap_Mmap2Stream_0_ARQOS;
  input m_axi_mmap_Mmap2Stream_0_ARREADY;
  output [2:0] m_axi_mmap_Mmap2Stream_0_ARSIZE;
  output m_axi_mmap_Mmap2Stream_0_ARVALID;
  output [63:0] m_axi_mmap_Mmap2Stream_0_AWADDR;
  output [1:0] m_axi_mmap_Mmap2Stream_0_AWBURST;
  output [3:0] m_axi_mmap_Mmap2Stream_0_AWCACHE;
  output [0:0] m_axi_mmap_Mmap2Stream_0_AWID;
  output [7:0] m_axi_mmap_Mmap2Stream_0_AWLEN;
  output m_axi_mmap_Mmap2Stream_0_AWLOCK;
  output [2:0] m_axi_mmap_Mmap2Stream_0_AWPROT;
  output [3:0] m_axi_mmap_Mmap2Stream_0_AWQOS;
  input m_axi_mmap_Mmap2Stream_0_AWREADY;
  output [2:0] m_axi_mmap_Mmap2Stream_0_AWSIZE;
  output m_axi_mmap_Mmap2Stream_0_AWVALID;
  input [0:0] m_axi_mmap_Mmap2Stream_0_BID;
  output m_axi_mmap_Mmap2Stream_0_BREADY;
  input [1:0] m_axi_mmap_Mmap2Stream_0_BRESP;
  input m_axi_mmap_Mmap2Stream_0_BVALID;
  input [31:0] m_axi_mmap_Mmap2Stream_0_RDATA;
  input [0:0] m_axi_mmap_Mmap2Stream_0_RID;
  input m_axi_mmap_Mmap2Stream_0_RLAST;
  output m_axi_mmap_Mmap2Stream_0_RREADY;
  input [1:0] m_axi_mmap_Mmap2Stream_0_RRESP;
  input m_axi_mmap_Mmap2Stream_0_RVALID;
  output [31:0] m_axi_mmap_Mmap2Stream_0_WDATA;
  output m_axi_mmap_Mmap2Stream_0_WLAST;
  input m_axi_mmap_Mmap2Stream_0_WREADY;
  output [3:0] m_axi_mmap_Mmap2Stream_0_WSTRB;
  output m_axi_mmap_Mmap2Stream_0_WVALID;

reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;
  wire ap_rst_n_inv;
  wire ap_done;
  wire ap_idle;
  wire ap_ready;
  wire [32:0] a_q_VecAdd__din;
  wire a_q_VecAdd__full_n;
  wire a_q_VecAdd__write;
  wire [63:0] Mmap2Stream_0___mmap_Mmap2Stream_0__q0;
  wire [63:0] Mmap2Stream_0___n__q0;
  wire Mmap2Stream_0__ap_start;
  wire Mmap2Stream_0__ap_ready;
  wire Mmap2Stream_0__ap_done;
  wire Mmap2Stream_0__ap_idle;
// power-on initialization
  assign ap_rst_n_inv = (~ap_rst_n);
  assign a_q_VecAdd_s_din = a_q_VecAdd__din;
  assign a_q_VecAdd__full_n = a_q_VecAdd_s_full_n;
  assign a_q_VecAdd_s_write = a_q_VecAdd__write;

Mmap2Stream
Mmap2Stream_0
(
  .ap_clk(ap_clk),
  .ap_rst_n(ap_rst_n),
  .ap_start(Mmap2Stream_0__ap_start),
  .ap_done(Mmap2Stream_0__ap_done),
  .ap_idle(Mmap2Stream_0__ap_idle),
  .ap_ready(Mmap2Stream_0__ap_ready),
  .stream_s_din(a_q_VecAdd__din),
  .stream_s_full_n(a_q_VecAdd__full_n),
  .stream_s_write(a_q_VecAdd__write),
  .m_axi_mmap_ARADDR(m_axi_mmap_Mmap2Stream_0_ARADDR),
  .m_axi_mmap_ARBURST(m_axi_mmap_Mmap2Stream_0_ARBURST),
  .m_axi_mmap_ARID(m_axi_mmap_Mmap2Stream_0_ARID),
  .m_axi_mmap_ARLEN(m_axi_mmap_Mmap2Stream_0_ARLEN),
  .m_axi_mmap_ARREADY(m_axi_mmap_Mmap2Stream_0_ARREADY),
  .m_axi_mmap_ARSIZE(m_axi_mmap_Mmap2Stream_0_ARSIZE),
  .m_axi_mmap_ARVALID(m_axi_mmap_Mmap2Stream_0_ARVALID),
  .m_axi_mmap_AWADDR(m_axi_mmap_Mmap2Stream_0_AWADDR),
  .m_axi_mmap_AWBURST(m_axi_mmap_Mmap2Stream_0_AWBURST),
  .m_axi_mmap_AWID(m_axi_mmap_Mmap2Stream_0_AWID),
  .m_axi_mmap_AWLEN(m_axi_mmap_Mmap2Stream_0_AWLEN),
  .m_axi_mmap_AWREADY(m_axi_mmap_Mmap2Stream_0_AWREADY),
  .m_axi_mmap_AWSIZE(m_axi_mmap_Mmap2Stream_0_AWSIZE),
  .m_axi_mmap_AWVALID(m_axi_mmap_Mmap2Stream_0_AWVALID),
  .m_axi_mmap_BID(m_axi_mmap_Mmap2Stream_0_BID),
  .m_axi_mmap_BREADY(m_axi_mmap_Mmap2Stream_0_BREADY),
  .m_axi_mmap_BRESP(m_axi_mmap_Mmap2Stream_0_BRESP),
  .m_axi_mmap_BVALID(m_axi_mmap_Mmap2Stream_0_BVALID),
  .m_axi_mmap_RDATA(m_axi_mmap_Mmap2Stream_0_RDATA),
  .m_axi_mmap_RID(m_axi_mmap_Mmap2Stream_0_RID),
  .m_axi_mmap_RLAST(m_axi_mmap_Mmap2Stream_0_RLAST),
  .m_axi_mmap_RREADY(m_axi_mmap_Mmap2Stream_0_RREADY),
  .m_axi_mmap_RRESP(m_axi_mmap_Mmap2Stream_0_RRESP),
  .m_axi_mmap_RVALID(m_axi_mmap_Mmap2Stream_0_RVALID),
  .m_axi_mmap_WDATA(m_axi_mmap_Mmap2Stream_0_WDATA),
  .m_axi_mmap_WLAST(m_axi_mmap_Mmap2Stream_0_WLAST),
  .m_axi_mmap_WREADY(m_axi_mmap_Mmap2Stream_0_WREADY),
  .m_axi_mmap_WSTRB(m_axi_mmap_Mmap2Stream_0_WSTRB),
  .m_axi_mmap_WVALID(m_axi_mmap_Mmap2Stream_0_WVALID),
  .m_axi_mmap_ARLOCK(m_axi_mmap_Mmap2Stream_0_ARLOCK),
  .m_axi_mmap_ARPROT(m_axi_mmap_Mmap2Stream_0_ARPROT),
  .m_axi_mmap_ARQOS(m_axi_mmap_Mmap2Stream_0_ARQOS),
  .m_axi_mmap_ARCACHE(m_axi_mmap_Mmap2Stream_0_ARCACHE),
  .m_axi_mmap_AWCACHE(m_axi_mmap_Mmap2Stream_0_AWCACHE),
  .m_axi_mmap_AWLOCK(m_axi_mmap_Mmap2Stream_0_AWLOCK),
  .m_axi_mmap_AWPROT(m_axi_mmap_Mmap2Stream_0_AWPROT),
  .m_axi_mmap_AWQOS(m_axi_mmap_Mmap2Stream_0_AWQOS),
  .mmap_offset(Mmap2Stream_0___mmap_Mmap2Stream_0__q0),
  .n(Mmap2Stream_0___n__q0)
);

SLOT_X0Y2_SLOT_X0Y2_fsm
__tapa_fsm_unit
(
  .ap_clk(ap_clk),
  .ap_rst_n(ap_rst_n),
  .ap_start(ap_start),
  .ap_done(ap_done),
  .ap_idle(ap_idle),
  .ap_ready(ap_ready),
  .mmap_Mmap2Stream_0(mmap_Mmap2Stream_0),
  .n(n),
  .Mmap2Stream_0___mmap_Mmap2Stream_0__q0(Mmap2Stream_0___mmap_Mmap2Stream_0__q0),
  .Mmap2Stream_0___n__q0(Mmap2Stream_0___n__q0),
  .Mmap2Stream_0__ap_start(Mmap2Stream_0__ap_start),
  .Mmap2Stream_0__ap_ready(Mmap2Stream_0__ap_ready),
  .Mmap2Stream_0__ap_done(Mmap2Stream_0__ap_done),
  .Mmap2Stream_0__ap_idle(Mmap2Stream_0__ap_idle)
);
endmodule
