// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

(* CORE_GENERATION_INFO="SLOT_X2Y3_SLOT_X2Y3_SLOT_X2Y3_SLOT_X2Y3,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.215450,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=23,HLS_VERSION=2024_2}" *)
module SLOT_X2Y3_SLOT_X2Y3 (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        c,
        n,
        c_q_VecAdd_s_dout,
        c_q_VecAdd_s_empty_n,
        c_q_VecAdd_s_read,
        c_q_VecAdd_peek,
        mmap_Stream2Mmap_0
,
  m_axi_mmap_Stream2Mmap_0_ARADDR,
  m_axi_mmap_Stream2Mmap_0_ARBURST,
  m_axi_mmap_Stream2Mmap_0_ARCACHE,
  m_axi_mmap_Stream2Mmap_0_ARID,
  m_axi_mmap_Stream2Mmap_0_ARLEN,
  m_axi_mmap_Stream2Mmap_0_ARLOCK,
  m_axi_mmap_Stream2Mmap_0_ARPROT,
  m_axi_mmap_Stream2Mmap_0_ARQOS,
  m_axi_mmap_Stream2Mmap_0_ARREADY,
  m_axi_mmap_Stream2Mmap_0_ARSIZE,
  m_axi_mmap_Stream2Mmap_0_ARVALID,
  m_axi_mmap_Stream2Mmap_0_AWADDR,
  m_axi_mmap_Stream2Mmap_0_AWBURST,
  m_axi_mmap_Stream2Mmap_0_AWCACHE,
  m_axi_mmap_Stream2Mmap_0_AWID,
  m_axi_mmap_Stream2Mmap_0_AWLEN,
  m_axi_mmap_Stream2Mmap_0_AWLOCK,
  m_axi_mmap_Stream2Mmap_0_AWPROT,
  m_axi_mmap_Stream2Mmap_0_AWQOS,
  m_axi_mmap_Stream2Mmap_0_AWREADY,
  m_axi_mmap_Stream2Mmap_0_AWSIZE,
  m_axi_mmap_Stream2Mmap_0_AWVALID,
  m_axi_mmap_Stream2Mmap_0_BID,
  m_axi_mmap_Stream2Mmap_0_BREADY,
  m_axi_mmap_Stream2Mmap_0_BRESP,
  m_axi_mmap_Stream2Mmap_0_BVALID,
  m_axi_mmap_Stream2Mmap_0_RDATA,
  m_axi_mmap_Stream2Mmap_0_RID,
  m_axi_mmap_Stream2Mmap_0_RLAST,
  m_axi_mmap_Stream2Mmap_0_RREADY,
  m_axi_mmap_Stream2Mmap_0_RRESP,
  m_axi_mmap_Stream2Mmap_0_RVALID,
  m_axi_mmap_Stream2Mmap_0_WDATA,
  m_axi_mmap_Stream2Mmap_0_WLAST,
  m_axi_mmap_Stream2Mmap_0_WREADY,
  m_axi_mmap_Stream2Mmap_0_WSTRB,
  m_axi_mmap_Stream2Mmap_0_WVALID);
input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] c;
input  [63:0] n;
input  [32:0] c_q_VecAdd_s_dout;
input   c_q_VecAdd_s_empty_n;
output   c_q_VecAdd_s_read;
input  [32:0] c_q_VecAdd_peek;
input  [63:0] mmap_Stream2Mmap_0;
  output [63:0] m_axi_mmap_Stream2Mmap_0_ARADDR;
  output [1:0] m_axi_mmap_Stream2Mmap_0_ARBURST;
  output [3:0] m_axi_mmap_Stream2Mmap_0_ARCACHE;
  output [0:0] m_axi_mmap_Stream2Mmap_0_ARID;
  output [7:0] m_axi_mmap_Stream2Mmap_0_ARLEN;
  output m_axi_mmap_Stream2Mmap_0_ARLOCK;
  output [2:0] m_axi_mmap_Stream2Mmap_0_ARPROT;
  output [3:0] m_axi_mmap_Stream2Mmap_0_ARQOS;
  input m_axi_mmap_Stream2Mmap_0_ARREADY;
  output [2:0] m_axi_mmap_Stream2Mmap_0_ARSIZE;
  output m_axi_mmap_Stream2Mmap_0_ARVALID;
  output [63:0] m_axi_mmap_Stream2Mmap_0_AWADDR;
  output [1:0] m_axi_mmap_Stream2Mmap_0_AWBURST;
  output [3:0] m_axi_mmap_Stream2Mmap_0_AWCACHE;
  output [0:0] m_axi_mmap_Stream2Mmap_0_AWID;
  output [7:0] m_axi_mmap_Stream2Mmap_0_AWLEN;
  output m_axi_mmap_Stream2Mmap_0_AWLOCK;
  output [2:0] m_axi_mmap_Stream2Mmap_0_AWPROT;
  output [3:0] m_axi_mmap_Stream2Mmap_0_AWQOS;
  input m_axi_mmap_Stream2Mmap_0_AWREADY;
  output [2:0] m_axi_mmap_Stream2Mmap_0_AWSIZE;
  output m_axi_mmap_Stream2Mmap_0_AWVALID;
  input [0:0] m_axi_mmap_Stream2Mmap_0_BID;
  output m_axi_mmap_Stream2Mmap_0_BREADY;
  input [1:0] m_axi_mmap_Stream2Mmap_0_BRESP;
  input m_axi_mmap_Stream2Mmap_0_BVALID;
  input [31:0] m_axi_mmap_Stream2Mmap_0_RDATA;
  input [0:0] m_axi_mmap_Stream2Mmap_0_RID;
  input m_axi_mmap_Stream2Mmap_0_RLAST;
  output m_axi_mmap_Stream2Mmap_0_RREADY;
  input [1:0] m_axi_mmap_Stream2Mmap_0_RRESP;
  input m_axi_mmap_Stream2Mmap_0_RVALID;
  output [31:0] m_axi_mmap_Stream2Mmap_0_WDATA;
  output m_axi_mmap_Stream2Mmap_0_WLAST;
  input m_axi_mmap_Stream2Mmap_0_WREADY;
  output [3:0] m_axi_mmap_Stream2Mmap_0_WSTRB;
  output m_axi_mmap_Stream2Mmap_0_WVALID;

reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;
  wire ap_rst_n_inv;
  wire ap_done;
  wire ap_idle;
  wire ap_ready;
  wire [32:0] c_q_VecAdd__dout;
  wire c_q_VecAdd__empty_n;
  wire c_q_VecAdd__read;
  wire [63:0] Stream2Mmap_0___mmap_Stream2Mmap_0__q0;
  wire [63:0] Stream2Mmap_0___n__q0;
  wire Stream2Mmap_0__ap_start;
  wire Stream2Mmap_0__ap_ready;
  wire Stream2Mmap_0__ap_done;
  wire Stream2Mmap_0__ap_idle;
// power-on initialization
  assign ap_rst_n_inv = (~ap_rst_n);
  assign c_q_VecAdd__dout = c_q_VecAdd_s_dout;
  assign c_q_VecAdd__empty_n = c_q_VecAdd_s_empty_n;
  assign c_q_VecAdd_s_read = c_q_VecAdd__read;

Stream2Mmap
Stream2Mmap_0
(
  .ap_clk(ap_clk),
  .ap_rst_n(ap_rst_n),
  .ap_start(Stream2Mmap_0__ap_start),
  .ap_done(Stream2Mmap_0__ap_done),
  .ap_idle(Stream2Mmap_0__ap_idle),
  .ap_ready(Stream2Mmap_0__ap_ready),
  .stream_s_dout(c_q_VecAdd__dout),
  .stream_peek_dout(c_q_VecAdd__dout),
  .stream_s_empty_n(c_q_VecAdd__empty_n),
  .stream_peek_empty_n(c_q_VecAdd__empty_n),
  .stream_s_read(c_q_VecAdd__read),
  .m_axi_mmap_ARADDR(m_axi_mmap_Stream2Mmap_0_ARADDR),
  .m_axi_mmap_ARBURST(m_axi_mmap_Stream2Mmap_0_ARBURST),
  .m_axi_mmap_ARID(m_axi_mmap_Stream2Mmap_0_ARID),
  .m_axi_mmap_ARLEN(m_axi_mmap_Stream2Mmap_0_ARLEN),
  .m_axi_mmap_ARREADY(m_axi_mmap_Stream2Mmap_0_ARREADY),
  .m_axi_mmap_ARSIZE(m_axi_mmap_Stream2Mmap_0_ARSIZE),
  .m_axi_mmap_ARVALID(m_axi_mmap_Stream2Mmap_0_ARVALID),
  .m_axi_mmap_AWADDR(m_axi_mmap_Stream2Mmap_0_AWADDR),
  .m_axi_mmap_AWBURST(m_axi_mmap_Stream2Mmap_0_AWBURST),
  .m_axi_mmap_AWID(m_axi_mmap_Stream2Mmap_0_AWID),
  .m_axi_mmap_AWLEN(m_axi_mmap_Stream2Mmap_0_AWLEN),
  .m_axi_mmap_AWREADY(m_axi_mmap_Stream2Mmap_0_AWREADY),
  .m_axi_mmap_AWSIZE(m_axi_mmap_Stream2Mmap_0_AWSIZE),
  .m_axi_mmap_AWVALID(m_axi_mmap_Stream2Mmap_0_AWVALID),
  .m_axi_mmap_BID(m_axi_mmap_Stream2Mmap_0_BID),
  .m_axi_mmap_BREADY(m_axi_mmap_Stream2Mmap_0_BREADY),
  .m_axi_mmap_BRESP(m_axi_mmap_Stream2Mmap_0_BRESP),
  .m_axi_mmap_BVALID(m_axi_mmap_Stream2Mmap_0_BVALID),
  .m_axi_mmap_RDATA(m_axi_mmap_Stream2Mmap_0_RDATA),
  .m_axi_mmap_RID(m_axi_mmap_Stream2Mmap_0_RID),
  .m_axi_mmap_RLAST(m_axi_mmap_Stream2Mmap_0_RLAST),
  .m_axi_mmap_RREADY(m_axi_mmap_Stream2Mmap_0_RREADY),
  .m_axi_mmap_RRESP(m_axi_mmap_Stream2Mmap_0_RRESP),
  .m_axi_mmap_RVALID(m_axi_mmap_Stream2Mmap_0_RVALID),
  .m_axi_mmap_WDATA(m_axi_mmap_Stream2Mmap_0_WDATA),
  .m_axi_mmap_WLAST(m_axi_mmap_Stream2Mmap_0_WLAST),
  .m_axi_mmap_WREADY(m_axi_mmap_Stream2Mmap_0_WREADY),
  .m_axi_mmap_WSTRB(m_axi_mmap_Stream2Mmap_0_WSTRB),
  .m_axi_mmap_WVALID(m_axi_mmap_Stream2Mmap_0_WVALID),
  .m_axi_mmap_ARLOCK(m_axi_mmap_Stream2Mmap_0_ARLOCK),
  .m_axi_mmap_ARPROT(m_axi_mmap_Stream2Mmap_0_ARPROT),
  .m_axi_mmap_ARQOS(m_axi_mmap_Stream2Mmap_0_ARQOS),
  .m_axi_mmap_ARCACHE(m_axi_mmap_Stream2Mmap_0_ARCACHE),
  .m_axi_mmap_AWCACHE(m_axi_mmap_Stream2Mmap_0_AWCACHE),
  .m_axi_mmap_AWLOCK(m_axi_mmap_Stream2Mmap_0_AWLOCK),
  .m_axi_mmap_AWPROT(m_axi_mmap_Stream2Mmap_0_AWPROT),
  .m_axi_mmap_AWQOS(m_axi_mmap_Stream2Mmap_0_AWQOS),
  .mmap_offset(Stream2Mmap_0___mmap_Stream2Mmap_0__q0),
  .n(Stream2Mmap_0___n__q0)
);

SLOT_X2Y3_SLOT_X2Y3_fsm
__tapa_fsm_unit
(
  .ap_clk(ap_clk),
  .ap_rst_n(ap_rst_n),
  .ap_start(ap_start),
  .ap_done(ap_done),
  .ap_idle(ap_idle),
  .ap_ready(ap_ready),
  .mmap_Stream2Mmap_0(mmap_Stream2Mmap_0),
  .n(n),
  .Stream2Mmap_0___mmap_Stream2Mmap_0__q0(Stream2Mmap_0___mmap_Stream2Mmap_0__q0),
  .Stream2Mmap_0___n__q0(Stream2Mmap_0___n__q0),
  .Stream2Mmap_0__ap_start(Stream2Mmap_0__ap_start),
  .Stream2Mmap_0__ap_ready(Stream2Mmap_0__ap_ready),
  .Stream2Mmap_0__ap_done(Stream2Mmap_0__ap_done),
  .Stream2Mmap_0__ap_idle(Stream2Mmap_0__ap_idle)
);
endmodule
