// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

(* CORE_GENERATION_INFO="VecAdd_VecAdd,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=316,HLS_SYN_LUT=552,HLS_VERSION=2024_2}" *)
module VecAdd (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt
,
  m_axi_a_ARADDR,
  m_axi_a_ARBURST,
  m_axi_a_ARCACHE,
  m_axi_a_ARID,
  m_axi_a_ARLEN,
  m_axi_a_ARLOCK,
  m_axi_a_ARPROT,
  m_axi_a_ARQOS,
  m_axi_a_ARREADY,
  m_axi_a_ARSIZE,
  m_axi_a_ARVALID,
  m_axi_a_AWADDR,
  m_axi_a_AWBURST,
  m_axi_a_AWCACHE,
  m_axi_a_AWID,
  m_axi_a_AWLEN,
  m_axi_a_AWLOCK,
  m_axi_a_AWPROT,
  m_axi_a_AWQOS,
  m_axi_a_AWREADY,
  m_axi_a_AWSIZE,
  m_axi_a_AWVALID,
  m_axi_a_BID,
  m_axi_a_BREADY,
  m_axi_a_BRESP,
  m_axi_a_BVALID,
  m_axi_a_RDATA,
  m_axi_a_RID,
  m_axi_a_RLAST,
  m_axi_a_RREADY,
  m_axi_a_RRESP,
  m_axi_a_RVALID,
  m_axi_a_WDATA,
  m_axi_a_WLAST,
  m_axi_a_WREADY,
  m_axi_a_WSTRB,
  m_axi_a_WVALID,
  m_axi_c_ARADDR,
  m_axi_c_ARBURST,
  m_axi_c_ARCACHE,
  m_axi_c_ARID,
  m_axi_c_ARLEN,
  m_axi_c_ARLOCK,
  m_axi_c_ARPROT,
  m_axi_c_ARQOS,
  m_axi_c_ARREADY,
  m_axi_c_ARSIZE,
  m_axi_c_ARVALID,
  m_axi_c_AWADDR,
  m_axi_c_AWBURST,
  m_axi_c_AWCACHE,
  m_axi_c_AWID,
  m_axi_c_AWLEN,
  m_axi_c_AWLOCK,
  m_axi_c_AWPROT,
  m_axi_c_AWQOS,
  m_axi_c_AWREADY,
  m_axi_c_AWSIZE,
  m_axi_c_AWVALID,
  m_axi_c_BID,
  m_axi_c_BREADY,
  m_axi_c_BRESP,
  m_axi_c_BVALID,
  m_axi_c_RDATA,
  m_axi_c_RID,
  m_axi_c_RLAST,
  m_axi_c_RREADY,
  m_axi_c_RRESP,
  m_axi_c_RVALID,
  m_axi_c_WDATA,
  m_axi_c_WLAST,
  m_axi_c_WREADY,
  m_axi_c_WSTRB,
  m_axi_c_WVALID,
  m_axi_b_ARADDR,
  m_axi_b_ARBURST,
  m_axi_b_ARCACHE,
  m_axi_b_ARID,
  m_axi_b_ARLEN,
  m_axi_b_ARLOCK,
  m_axi_b_ARPROT,
  m_axi_b_ARQOS,
  m_axi_b_ARREADY,
  m_axi_b_ARSIZE,
  m_axi_b_ARVALID,
  m_axi_b_AWADDR,
  m_axi_b_AWBURST,
  m_axi_b_AWCACHE,
  m_axi_b_AWID,
  m_axi_b_AWLEN,
  m_axi_b_AWLOCK,
  m_axi_b_AWPROT,
  m_axi_b_AWQOS,
  m_axi_b_AWREADY,
  m_axi_b_AWSIZE,
  m_axi_b_AWVALID,
  m_axi_b_BID,
  m_axi_b_BREADY,
  m_axi_b_BRESP,
  m_axi_b_BVALID,
  m_axi_b_RDATA,
  m_axi_b_RID,
  m_axi_b_RLAST,
  m_axi_b_RREADY,
  m_axi_b_RRESP,
  m_axi_b_RVALID,
  m_axi_b_WDATA,
  m_axi_b_WLAST,
  m_axi_b_WREADY,
  m_axi_b_WSTRB,
  m_axi_b_WVALID);
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
(* RS_HS = "s_axi_control_AW.valid" *)input   s_axi_control_AWVALID;
(* RS_HS = "s_axi_control_AW.ready" *)output   s_axi_control_AWREADY;
(* RS_HS = "s_axi_control_AW.data" *)input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
(* RS_HS = "s_axi_control_W.valid" *)input   s_axi_control_WVALID;
(* RS_HS = "s_axi_control_W.ready" *)output   s_axi_control_WREADY;
(* RS_HS = "s_axi_control_W.data" *)input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
(* RS_HS = "s_axi_control_W.data" *)input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
(* RS_HS = "s_axi_control_AR.valid" *)input   s_axi_control_ARVALID;
(* RS_HS = "s_axi_control_AR.ready" *)output   s_axi_control_ARREADY;
(* RS_HS = "s_axi_control_AR.data" *)input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
(* RS_HS = "s_axi_control_R.valid" *)output   s_axi_control_RVALID;
(* RS_HS = "s_axi_control_R.ready" *)input   s_axi_control_RREADY;
(* RS_HS = "s_axi_control_R.data" *)output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
(* RS_HS = "s_axi_control_R.data" *)output  [1:0] s_axi_control_RRESP;
(* RS_HS = "s_axi_control_B.valid" *)output   s_axi_control_BVALID;
(* RS_HS = "s_axi_control_B.ready" *)input   s_axi_control_BREADY;
(* RS_HS = "s_axi_control_B.data" *)output  [1:0] s_axi_control_BRESP;
(* RS_CLK *)input   ap_clk;
(* RS_RST = "ff" *)input   ap_rst_n;
(* RS_FF = "interrupt" *)output   interrupt;
  output [63:0] m_axi_a_ARADDR;
  output [1:0] m_axi_a_ARBURST;
  output [3:0] m_axi_a_ARCACHE;
  output [0:0] m_axi_a_ARID;
  output [7:0] m_axi_a_ARLEN;
  output m_axi_a_ARLOCK;
  output [2:0] m_axi_a_ARPROT;
  output [3:0] m_axi_a_ARQOS;
  input m_axi_a_ARREADY;
  output [2:0] m_axi_a_ARSIZE;
  output m_axi_a_ARVALID;
  output [63:0] m_axi_a_AWADDR;
  output [1:0] m_axi_a_AWBURST;
  output [3:0] m_axi_a_AWCACHE;
  output [0:0] m_axi_a_AWID;
  output [7:0] m_axi_a_AWLEN;
  output m_axi_a_AWLOCK;
  output [2:0] m_axi_a_AWPROT;
  output [3:0] m_axi_a_AWQOS;
  input m_axi_a_AWREADY;
  output [2:0] m_axi_a_AWSIZE;
  output m_axi_a_AWVALID;
  input [0:0] m_axi_a_BID;
  output m_axi_a_BREADY;
  input [1:0] m_axi_a_BRESP;
  input m_axi_a_BVALID;
  input [31:0] m_axi_a_RDATA;
  input [0:0] m_axi_a_RID;
  input m_axi_a_RLAST;
  output m_axi_a_RREADY;
  input [1:0] m_axi_a_RRESP;
  input m_axi_a_RVALID;
  output [31:0] m_axi_a_WDATA;
  output m_axi_a_WLAST;
  input m_axi_a_WREADY;
  output [3:0] m_axi_a_WSTRB;
  output m_axi_a_WVALID;
  output [63:0] m_axi_c_ARADDR;
  output [1:0] m_axi_c_ARBURST;
  output [3:0] m_axi_c_ARCACHE;
  output [0:0] m_axi_c_ARID;
  output [7:0] m_axi_c_ARLEN;
  output m_axi_c_ARLOCK;
  output [2:0] m_axi_c_ARPROT;
  output [3:0] m_axi_c_ARQOS;
  input m_axi_c_ARREADY;
  output [2:0] m_axi_c_ARSIZE;
  output m_axi_c_ARVALID;
  output [63:0] m_axi_c_AWADDR;
  output [1:0] m_axi_c_AWBURST;
  output [3:0] m_axi_c_AWCACHE;
  output [0:0] m_axi_c_AWID;
  output [7:0] m_axi_c_AWLEN;
  output m_axi_c_AWLOCK;
  output [2:0] m_axi_c_AWPROT;
  output [3:0] m_axi_c_AWQOS;
  input m_axi_c_AWREADY;
  output [2:0] m_axi_c_AWSIZE;
  output m_axi_c_AWVALID;
  input [0:0] m_axi_c_BID;
  output m_axi_c_BREADY;
  input [1:0] m_axi_c_BRESP;
  input m_axi_c_BVALID;
  input [31:0] m_axi_c_RDATA;
  input [0:0] m_axi_c_RID;
  input m_axi_c_RLAST;
  output m_axi_c_RREADY;
  input [1:0] m_axi_c_RRESP;
  input m_axi_c_RVALID;
  output [31:0] m_axi_c_WDATA;
  output m_axi_c_WLAST;
  input m_axi_c_WREADY;
  output [3:0] m_axi_c_WSTRB;
  output m_axi_c_WVALID;
  output [63:0] m_axi_b_ARADDR;
  output [1:0] m_axi_b_ARBURST;
  output [3:0] m_axi_b_ARCACHE;
  output [0:0] m_axi_b_ARID;
  output [7:0] m_axi_b_ARLEN;
  output m_axi_b_ARLOCK;
  output [2:0] m_axi_b_ARPROT;
  output [3:0] m_axi_b_ARQOS;
  input m_axi_b_ARREADY;
  output [2:0] m_axi_b_ARSIZE;
  output m_axi_b_ARVALID;
  output [63:0] m_axi_b_AWADDR;
  output [1:0] m_axi_b_AWBURST;
  output [3:0] m_axi_b_AWCACHE;
  output [0:0] m_axi_b_AWID;
  output [7:0] m_axi_b_AWLEN;
  output m_axi_b_AWLOCK;
  output [2:0] m_axi_b_AWPROT;
  output [3:0] m_axi_b_AWQOS;
  input m_axi_b_AWREADY;
  output [2:0] m_axi_b_AWSIZE;
  output m_axi_b_AWVALID;
  input [0:0] m_axi_b_BID;
  output m_axi_b_BREADY;
  input [1:0] m_axi_b_BRESP;
  input m_axi_b_BVALID;
  input [31:0] m_axi_b_RDATA;
  input [0:0] m_axi_b_RID;
  input m_axi_b_RLAST;
  output m_axi_b_RREADY;
  input [1:0] m_axi_b_RRESP;
  input m_axi_b_RVALID;
  output [31:0] m_axi_b_WDATA;
  output m_axi_b_WLAST;
  input m_axi_b_WREADY;
  output [3:0] m_axi_b_WSTRB;
  output m_axi_b_WVALID;
wire    ap_start;
wire   [63:0] a;
wire   [63:0] b;
wire   [63:0] c;
wire   [63:0] n;

  wire ap_rst_n_inv;
  wire ap_done;
  wire ap_idle;
  wire ap_ready;
  wire [32:0] a_q_VecAdd__dout;
  wire a_q_VecAdd__empty_n;
  wire a_q_VecAdd__read;
  wire [32:0] a_q_VecAdd__din;
  wire a_q_VecAdd__full_n;
  wire a_q_VecAdd__write;
  wire [32:0] c_q_VecAdd__dout;
  wire c_q_VecAdd__empty_n;
  wire c_q_VecAdd__read;
  wire [32:0] c_q_VecAdd__din;
  wire c_q_VecAdd__full_n;
  wire c_q_VecAdd__write;
  wire [63:0] SLOT_X0Y2_SLOT_X0Y2_0___a__q0;
  wire [63:0] SLOT_X0Y2_SLOT_X0Y2_0___n__q0;
  wire SLOT_X0Y2_SLOT_X0Y2_0__ap_start;
  wire SLOT_X0Y2_SLOT_X0Y2_0__ap_ready;
  wire SLOT_X0Y2_SLOT_X0Y2_0__ap_done;
  wire SLOT_X0Y2_SLOT_X0Y2_0__ap_idle;
  wire [63:0] SLOT_X2Y3_SLOT_X2Y3_0___c__q0;
  wire [63:0] SLOT_X2Y3_SLOT_X2Y3_0___n__q0;
  wire SLOT_X2Y3_SLOT_X2Y3_0__ap_start;
  wire SLOT_X2Y3_SLOT_X2Y3_0__ap_ready;
  wire SLOT_X2Y3_SLOT_X2Y3_0__ap_done;
  wire SLOT_X2Y3_SLOT_X2Y3_0__ap_idle;
  wire [63:0] SLOT_X3Y3_SLOT_X3Y3_0___b__q0;
  wire [63:0] SLOT_X3Y3_SLOT_X3Y3_0___n__q0;
  wire SLOT_X3Y3_SLOT_X3Y3_0__ap_start;
  wire SLOT_X3Y3_SLOT_X3Y3_0__ap_ready;
  wire SLOT_X3Y3_SLOT_X3Y3_0__ap_done;
  wire SLOT_X3Y3_SLOT_X3Y3_0__ap_idle;
VecAdd_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .a(a),
    .b(b),
    .c(c),
    .n(n),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);
  assign ap_rst_n_inv = (~ap_rst_n);

fifo
#(
  .DATA_WIDTH(32 - 0 + 1),
  .ADDR_WIDTH(1),
  .DEPTH(2)
)
a_q_VecAdd
(
  .clk(ap_clk),
  .reset(~ap_rst_n),
  .if_dout(a_q_VecAdd__dout),
  .if_empty_n(a_q_VecAdd__empty_n),
  .if_read(a_q_VecAdd__read),
  .if_read_ce(1'b1),
  .if_din(a_q_VecAdd__din),
  .if_full_n(a_q_VecAdd__full_n),
  .if_write(a_q_VecAdd__write),
  .if_write_ce(1'b1)
);

fifo
#(
  .DATA_WIDTH(32 - 0 + 1),
  .ADDR_WIDTH(1),
  .DEPTH(2)
)
c_q_VecAdd
(
  .clk(ap_clk),
  .reset(~ap_rst_n),
  .if_dout(c_q_VecAdd__dout),
  .if_empty_n(c_q_VecAdd__empty_n),
  .if_read(c_q_VecAdd__read),
  .if_read_ce(1'b1),
  .if_din(c_q_VecAdd__din),
  .if_full_n(c_q_VecAdd__full_n),
  .if_write(c_q_VecAdd__write),
  .if_write_ce(1'b1)
);

SLOT_X0Y2_SLOT_X0Y2
SLOT_X0Y2_SLOT_X0Y2_0
(
  .ap_clk(ap_clk),
  .ap_rst_n(ap_rst_n),
  .ap_start(SLOT_X0Y2_SLOT_X0Y2_0__ap_start),
  .ap_done(SLOT_X0Y2_SLOT_X0Y2_0__ap_done),
  .ap_idle(SLOT_X0Y2_SLOT_X0Y2_0__ap_idle),
  .ap_ready(SLOT_X0Y2_SLOT_X0Y2_0__ap_ready),
  .m_axi_mmap_Mmap2Stream_0_ARADDR(m_axi_a_ARADDR),
  .m_axi_mmap_Mmap2Stream_0_ARBURST(m_axi_a_ARBURST),
  .m_axi_mmap_Mmap2Stream_0_ARID(m_axi_a_ARID),
  .m_axi_mmap_Mmap2Stream_0_ARLEN(m_axi_a_ARLEN),
  .m_axi_mmap_Mmap2Stream_0_ARREADY(m_axi_a_ARREADY),
  .m_axi_mmap_Mmap2Stream_0_ARSIZE(m_axi_a_ARSIZE),
  .m_axi_mmap_Mmap2Stream_0_ARVALID(m_axi_a_ARVALID),
  .m_axi_mmap_Mmap2Stream_0_AWADDR(m_axi_a_AWADDR),
  .m_axi_mmap_Mmap2Stream_0_AWBURST(m_axi_a_AWBURST),
  .m_axi_mmap_Mmap2Stream_0_AWID(m_axi_a_AWID),
  .m_axi_mmap_Mmap2Stream_0_AWLEN(m_axi_a_AWLEN),
  .m_axi_mmap_Mmap2Stream_0_AWREADY(m_axi_a_AWREADY),
  .m_axi_mmap_Mmap2Stream_0_AWSIZE(m_axi_a_AWSIZE),
  .m_axi_mmap_Mmap2Stream_0_AWVALID(m_axi_a_AWVALID),
  .m_axi_mmap_Mmap2Stream_0_BID(m_axi_a_BID),
  .m_axi_mmap_Mmap2Stream_0_BREADY(m_axi_a_BREADY),
  .m_axi_mmap_Mmap2Stream_0_BRESP(m_axi_a_BRESP),
  .m_axi_mmap_Mmap2Stream_0_BVALID(m_axi_a_BVALID),
  .m_axi_mmap_Mmap2Stream_0_RDATA(m_axi_a_RDATA),
  .m_axi_mmap_Mmap2Stream_0_RID(m_axi_a_RID),
  .m_axi_mmap_Mmap2Stream_0_RLAST(m_axi_a_RLAST),
  .m_axi_mmap_Mmap2Stream_0_RREADY(m_axi_a_RREADY),
  .m_axi_mmap_Mmap2Stream_0_RRESP(m_axi_a_RRESP),
  .m_axi_mmap_Mmap2Stream_0_RVALID(m_axi_a_RVALID),
  .m_axi_mmap_Mmap2Stream_0_WDATA(m_axi_a_WDATA),
  .m_axi_mmap_Mmap2Stream_0_WLAST(m_axi_a_WLAST),
  .m_axi_mmap_Mmap2Stream_0_WREADY(m_axi_a_WREADY),
  .m_axi_mmap_Mmap2Stream_0_WSTRB(m_axi_a_WSTRB),
  .m_axi_mmap_Mmap2Stream_0_WVALID(m_axi_a_WVALID),
  .m_axi_mmap_Mmap2Stream_0_ARLOCK(m_axi_a_ARLOCK),
  .m_axi_mmap_Mmap2Stream_0_ARPROT(m_axi_a_ARPROT),
  .m_axi_mmap_Mmap2Stream_0_ARQOS(m_axi_a_ARQOS),
  .m_axi_mmap_Mmap2Stream_0_ARCACHE(m_axi_a_ARCACHE),
  .m_axi_mmap_Mmap2Stream_0_AWCACHE(m_axi_a_AWCACHE),
  .m_axi_mmap_Mmap2Stream_0_AWLOCK(m_axi_a_AWLOCK),
  .m_axi_mmap_Mmap2Stream_0_AWPROT(m_axi_a_AWPROT),
  .m_axi_mmap_Mmap2Stream_0_AWQOS(m_axi_a_AWQOS),
  .mmap_Mmap2Stream_0(SLOT_X0Y2_SLOT_X0Y2_0___a__q0),
  .a_q_VecAdd_s_din(a_q_VecAdd__din),
  .a_q_VecAdd_s_full_n(a_q_VecAdd__full_n),
  .a_q_VecAdd_s_write(a_q_VecAdd__write),
  .n(SLOT_X0Y2_SLOT_X0Y2_0___n__q0)
);

SLOT_X2Y3_SLOT_X2Y3
SLOT_X2Y3_SLOT_X2Y3_0
(
  .ap_clk(ap_clk),
  .ap_rst_n(ap_rst_n),
  .ap_start(SLOT_X2Y3_SLOT_X2Y3_0__ap_start),
  .ap_done(SLOT_X2Y3_SLOT_X2Y3_0__ap_done),
  .ap_idle(SLOT_X2Y3_SLOT_X2Y3_0__ap_idle),
  .ap_ready(SLOT_X2Y3_SLOT_X2Y3_0__ap_ready),
  .m_axi_mmap_Stream2Mmap_0_ARADDR(m_axi_c_ARADDR),
  .m_axi_mmap_Stream2Mmap_0_ARBURST(m_axi_c_ARBURST),
  .m_axi_mmap_Stream2Mmap_0_ARID(m_axi_c_ARID),
  .m_axi_mmap_Stream2Mmap_0_ARLEN(m_axi_c_ARLEN),
  .m_axi_mmap_Stream2Mmap_0_ARREADY(m_axi_c_ARREADY),
  .m_axi_mmap_Stream2Mmap_0_ARSIZE(m_axi_c_ARSIZE),
  .m_axi_mmap_Stream2Mmap_0_ARVALID(m_axi_c_ARVALID),
  .m_axi_mmap_Stream2Mmap_0_AWADDR(m_axi_c_AWADDR),
  .m_axi_mmap_Stream2Mmap_0_AWBURST(m_axi_c_AWBURST),
  .m_axi_mmap_Stream2Mmap_0_AWID(m_axi_c_AWID),
  .m_axi_mmap_Stream2Mmap_0_AWLEN(m_axi_c_AWLEN),
  .m_axi_mmap_Stream2Mmap_0_AWREADY(m_axi_c_AWREADY),
  .m_axi_mmap_Stream2Mmap_0_AWSIZE(m_axi_c_AWSIZE),
  .m_axi_mmap_Stream2Mmap_0_AWVALID(m_axi_c_AWVALID),
  .m_axi_mmap_Stream2Mmap_0_BID(m_axi_c_BID),
  .m_axi_mmap_Stream2Mmap_0_BREADY(m_axi_c_BREADY),
  .m_axi_mmap_Stream2Mmap_0_BRESP(m_axi_c_BRESP),
  .m_axi_mmap_Stream2Mmap_0_BVALID(m_axi_c_BVALID),
  .m_axi_mmap_Stream2Mmap_0_RDATA(m_axi_c_RDATA),
  .m_axi_mmap_Stream2Mmap_0_RID(m_axi_c_RID),
  .m_axi_mmap_Stream2Mmap_0_RLAST(m_axi_c_RLAST),
  .m_axi_mmap_Stream2Mmap_0_RREADY(m_axi_c_RREADY),
  .m_axi_mmap_Stream2Mmap_0_RRESP(m_axi_c_RRESP),
  .m_axi_mmap_Stream2Mmap_0_RVALID(m_axi_c_RVALID),
  .m_axi_mmap_Stream2Mmap_0_WDATA(m_axi_c_WDATA),
  .m_axi_mmap_Stream2Mmap_0_WLAST(m_axi_c_WLAST),
  .m_axi_mmap_Stream2Mmap_0_WREADY(m_axi_c_WREADY),
  .m_axi_mmap_Stream2Mmap_0_WSTRB(m_axi_c_WSTRB),
  .m_axi_mmap_Stream2Mmap_0_WVALID(m_axi_c_WVALID),
  .m_axi_mmap_Stream2Mmap_0_ARLOCK(m_axi_c_ARLOCK),
  .m_axi_mmap_Stream2Mmap_0_ARPROT(m_axi_c_ARPROT),
  .m_axi_mmap_Stream2Mmap_0_ARQOS(m_axi_c_ARQOS),
  .m_axi_mmap_Stream2Mmap_0_ARCACHE(m_axi_c_ARCACHE),
  .m_axi_mmap_Stream2Mmap_0_AWCACHE(m_axi_c_AWCACHE),
  .m_axi_mmap_Stream2Mmap_0_AWLOCK(m_axi_c_AWLOCK),
  .m_axi_mmap_Stream2Mmap_0_AWPROT(m_axi_c_AWPROT),
  .m_axi_mmap_Stream2Mmap_0_AWQOS(m_axi_c_AWQOS),
  .mmap_Stream2Mmap_0(SLOT_X2Y3_SLOT_X2Y3_0___c__q0),
  .c_q_VecAdd_s_dout(c_q_VecAdd__dout),
  .c_q_VecAdd_s_empty_n(c_q_VecAdd__empty_n),
  .c_q_VecAdd_s_read(c_q_VecAdd__read),
  .n(SLOT_X2Y3_SLOT_X2Y3_0___n__q0)
);

SLOT_X3Y3_SLOT_X3Y3
SLOT_X3Y3_SLOT_X3Y3_0
(
  .ap_clk(ap_clk),
  .ap_rst_n(ap_rst_n),
  .ap_start(SLOT_X3Y3_SLOT_X3Y3_0__ap_start),
  .ap_done(SLOT_X3Y3_SLOT_X3Y3_0__ap_done),
  .ap_idle(SLOT_X3Y3_SLOT_X3Y3_0__ap_idle),
  .ap_ready(SLOT_X3Y3_SLOT_X3Y3_0__ap_ready),
  .a_q_VecAdd_s_dout(a_q_VecAdd__dout),
  .a_q_VecAdd_s_empty_n(a_q_VecAdd__empty_n),
  .a_q_VecAdd_s_read(a_q_VecAdd__read),
  .m_axi_mmap_Mmap2Stream_1_ARADDR(m_axi_b_ARADDR),
  .m_axi_mmap_Mmap2Stream_1_ARBURST(m_axi_b_ARBURST),
  .m_axi_mmap_Mmap2Stream_1_ARID(m_axi_b_ARID),
  .m_axi_mmap_Mmap2Stream_1_ARLEN(m_axi_b_ARLEN),
  .m_axi_mmap_Mmap2Stream_1_ARREADY(m_axi_b_ARREADY),
  .m_axi_mmap_Mmap2Stream_1_ARSIZE(m_axi_b_ARSIZE),
  .m_axi_mmap_Mmap2Stream_1_ARVALID(m_axi_b_ARVALID),
  .m_axi_mmap_Mmap2Stream_1_AWADDR(m_axi_b_AWADDR),
  .m_axi_mmap_Mmap2Stream_1_AWBURST(m_axi_b_AWBURST),
  .m_axi_mmap_Mmap2Stream_1_AWID(m_axi_b_AWID),
  .m_axi_mmap_Mmap2Stream_1_AWLEN(m_axi_b_AWLEN),
  .m_axi_mmap_Mmap2Stream_1_AWREADY(m_axi_b_AWREADY),
  .m_axi_mmap_Mmap2Stream_1_AWSIZE(m_axi_b_AWSIZE),
  .m_axi_mmap_Mmap2Stream_1_AWVALID(m_axi_b_AWVALID),
  .m_axi_mmap_Mmap2Stream_1_BID(m_axi_b_BID),
  .m_axi_mmap_Mmap2Stream_1_BREADY(m_axi_b_BREADY),
  .m_axi_mmap_Mmap2Stream_1_BRESP(m_axi_b_BRESP),
  .m_axi_mmap_Mmap2Stream_1_BVALID(m_axi_b_BVALID),
  .m_axi_mmap_Mmap2Stream_1_RDATA(m_axi_b_RDATA),
  .m_axi_mmap_Mmap2Stream_1_RID(m_axi_b_RID),
  .m_axi_mmap_Mmap2Stream_1_RLAST(m_axi_b_RLAST),
  .m_axi_mmap_Mmap2Stream_1_RREADY(m_axi_b_RREADY),
  .m_axi_mmap_Mmap2Stream_1_RRESP(m_axi_b_RRESP),
  .m_axi_mmap_Mmap2Stream_1_RVALID(m_axi_b_RVALID),
  .m_axi_mmap_Mmap2Stream_1_WDATA(m_axi_b_WDATA),
  .m_axi_mmap_Mmap2Stream_1_WLAST(m_axi_b_WLAST),
  .m_axi_mmap_Mmap2Stream_1_WREADY(m_axi_b_WREADY),
  .m_axi_mmap_Mmap2Stream_1_WSTRB(m_axi_b_WSTRB),
  .m_axi_mmap_Mmap2Stream_1_WVALID(m_axi_b_WVALID),
  .m_axi_mmap_Mmap2Stream_1_ARLOCK(m_axi_b_ARLOCK),
  .m_axi_mmap_Mmap2Stream_1_ARPROT(m_axi_b_ARPROT),
  .m_axi_mmap_Mmap2Stream_1_ARQOS(m_axi_b_ARQOS),
  .m_axi_mmap_Mmap2Stream_1_ARCACHE(m_axi_b_ARCACHE),
  .m_axi_mmap_Mmap2Stream_1_AWCACHE(m_axi_b_AWCACHE),
  .m_axi_mmap_Mmap2Stream_1_AWLOCK(m_axi_b_AWLOCK),
  .m_axi_mmap_Mmap2Stream_1_AWPROT(m_axi_b_AWPROT),
  .m_axi_mmap_Mmap2Stream_1_AWQOS(m_axi_b_AWQOS),
  .mmap_Mmap2Stream_1(SLOT_X3Y3_SLOT_X3Y3_0___b__q0),
  .c_q_VecAdd_s_din(c_q_VecAdd__din),
  .c_q_VecAdd_s_full_n(c_q_VecAdd__full_n),
  .c_q_VecAdd_s_write(c_q_VecAdd__write),
  .n(SLOT_X3Y3_SLOT_X3Y3_0___n__q0)
);

VecAdd_fsm
__tapa_fsm_unit
(
  .ap_clk(ap_clk),
  .ap_rst_n(ap_rst_n),
  .ap_start(ap_start),
  .ap_done(ap_done),
  .ap_idle(ap_idle),
  .ap_ready(ap_ready),
  .a(a),
  .n(n),
  .c(c),
  .b(b),
  .SLOT_X0Y2_SLOT_X0Y2_0___a__q0(SLOT_X0Y2_SLOT_X0Y2_0___a__q0),
  .SLOT_X0Y2_SLOT_X0Y2_0___n__q0(SLOT_X0Y2_SLOT_X0Y2_0___n__q0),
  .SLOT_X0Y2_SLOT_X0Y2_0__ap_start(SLOT_X0Y2_SLOT_X0Y2_0__ap_start),
  .SLOT_X0Y2_SLOT_X0Y2_0__ap_ready(SLOT_X0Y2_SLOT_X0Y2_0__ap_ready),
  .SLOT_X0Y2_SLOT_X0Y2_0__ap_done(SLOT_X0Y2_SLOT_X0Y2_0__ap_done),
  .SLOT_X0Y2_SLOT_X0Y2_0__ap_idle(SLOT_X0Y2_SLOT_X0Y2_0__ap_idle),
  .SLOT_X2Y3_SLOT_X2Y3_0___c__q0(SLOT_X2Y3_SLOT_X2Y3_0___c__q0),
  .SLOT_X2Y3_SLOT_X2Y3_0___n__q0(SLOT_X2Y3_SLOT_X2Y3_0___n__q0),
  .SLOT_X2Y3_SLOT_X2Y3_0__ap_start(SLOT_X2Y3_SLOT_X2Y3_0__ap_start),
  .SLOT_X2Y3_SLOT_X2Y3_0__ap_ready(SLOT_X2Y3_SLOT_X2Y3_0__ap_ready),
  .SLOT_X2Y3_SLOT_X2Y3_0__ap_done(SLOT_X2Y3_SLOT_X2Y3_0__ap_done),
  .SLOT_X2Y3_SLOT_X2Y3_0__ap_idle(SLOT_X2Y3_SLOT_X2Y3_0__ap_idle),
  .SLOT_X3Y3_SLOT_X3Y3_0___b__q0(SLOT_X3Y3_SLOT_X3Y3_0___b__q0),
  .SLOT_X3Y3_SLOT_X3Y3_0___n__q0(SLOT_X3Y3_SLOT_X3Y3_0___n__q0),
  .SLOT_X3Y3_SLOT_X3Y3_0__ap_start(SLOT_X3Y3_SLOT_X3Y3_0__ap_start),
  .SLOT_X3Y3_SLOT_X3Y3_0__ap_ready(SLOT_X3Y3_SLOT_X3Y3_0__ap_ready),
  .SLOT_X3Y3_SLOT_X3Y3_0__ap_done(SLOT_X3Y3_SLOT_X3Y3_0__ap_done),
  .SLOT_X3Y3_SLOT_X3Y3_0__ap_idle(SLOT_X3Y3_SLOT_X3Y3_0__ap_idle)
);
endmodule
