# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: "Publish the distributions"
description: "Publish the distributions to the Cloudflare Pages and R2"

inputs:
  channel:
    description: "Channel to publish the distribution for"
    required: true
  cloudflareToken:
    description: "Token for the Cloudflare"
    required: true
  cloudflareAccountID:
    description: "Account for the Cloudflare"
    required: false
    default: "848de03c597aa02475ca2f171acc9905"
  cloudflareR2BucketName:
    description: "Bucket name for the Cloudflare R2"
    required: false
    default: "rapidstream-releases"
  cloudflarePagesProjectName:
    description: "Project name of the Cloudflare Pages"
    required: false
    default: "rapidstream-tapa"

runs:
  using: "composite"
  steps:
    - name: Build docker image to use Cloudflare Wrangler
      uses: ./.github/actions/build-docker
      with:
        imageTag: rapidstream/cloudflare:local
        dockerfile: ./.github/docker/Dockerfile.cloudflare
        context: ./.github/docker

    - name: Publish the installer to Cloudflare Pages
      uses: ./.github/actions/run-docker
      with:
        image: rapidstream/cloudflare:local
        run: |
          cp install.sh .github/actions/publish-dist/installer/tapa.rapidstream.sh
          retry -- wrangler pages deploy \
            --project-name ${{ inputs.cloudflarePagesProjectName }} \
            .github/actions/publish-dist/installer
        dockerOptions: >-
          -e CLOUDFLARE_API_TOKEN=${{ inputs.cloudflareToken }}
          -e CLOUDFLARE_ACCOUNT_ID=${{ inputs.cloudflareAccountID }}

    - name: Upload the distribution files to Cloudflare R2
      uses: ./.github/actions/run-docker
      with:
        image: rapidstream/cloudflare:local
        run: |
          bucket="${{ inputs.cloudflareR2BucketName }}"
          channel="${{ inputs.channel }}"
          version="$(cat VERSION)"
          retry -- wrangler r2 object put \
            \$bucket/rapidstream-tapa-\$channel-latest.tar.gz \
            --file=/workspace/artifacts.out/tapa.tar.gz
          retry -- wrangler r2 object put \
            \$bucket/rapidstream-tapa-\$channel-\$version.tar.gz \
            --file=/workspace/artifacts.out/tapa.tar.gz
        dockerOptions: >-
          -e CLOUDFLARE_API_TOKEN=${{ inputs.cloudflareToken }}
          -e CLOUDFLARE_ACCOUNT_ID=${{ inputs.cloudflareAccountID }}
