"""Generate floorplan slot cpp for hls synth."""

__copyright__ = """
Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
All rights reserved. The contributor(s) of this file has/have agreed to the
RapidStream Contributor License Agreement.
"""

import pathlib
import re
from string import Template

_SCALAR_PRAGMA = (
    "#pragma HLS interface ap_none port = {name} register\n"
    "  {{ auto val = reinterpret_cast<volatile uint8_t &>({name}); }}"
)
_FIFO_IN_PRAGMA = (
    "#pragma HLS disaggregate variable = {name}\n"
    "#pragma HLS interface ap_fifo port = {name}._\n"
    "#pragma HLS aggregate variable = {name}._ bit\n"
    "  void({name}._.empty());\n"
    "  {{ auto val = {name}.read(); }}\n"
)
_FIFO_OUT_PRAGMA = (
    "#pragma HLS disaggregate variable = {name}\n"
    "#pragma HLS interface ap_fifo port = {name}._\n"
    "#pragma HLS aggregate variable = {name}._ bit\n"
    "  void({name}._.full());\n"
    "  {name}.write({type}());"
)

_PRAGMA = {
    "scalar": _SCALAR_PRAGMA,
    "mmap": _SCALAR_PRAGMA,
    "istream": _FIFO_IN_PRAGMA,
    "ostream": _FIFO_OUT_PRAGMA,
    "istreams": _FIFO_IN_PRAGMA,
    "ostreams": _FIFO_OUT_PRAGMA,
}

_SCALAR_PORT_TEMPLATE = "{type} {name}"
_PORT_TEMPLATE = {
    "istream": "tapa::istream<{type}>& {name}",
    "ostream": "tapa::ostream<{type}>& {name}",
    "istreams": "tapa::istream<{type}>& {name}",
    "ostreams": "tapa::ostream<{type}>& {name}",
    "scalar": _SCALAR_PORT_TEMPLATE,
    "mmap": _SCALAR_PORT_TEMPLATE,
    "async_mmap": _SCALAR_PORT_TEMPLATE,
}
_DEF_TEMPLATE_PATH = pathlib.Path(__file__).parent / "template/slot_def_template.txt"
_DECL_TEMPLATE_PATH = pathlib.Path(__file__).parent / "template/slot_decl_template.txt"


def gen_slot_cpp(slot_name: str, top_name: str, ports: list, top_cpp: str) -> str:
    """Generate floorplan slot cpp for hls synth.

    slot_name: Name of the slot
    ports: List of ports in the slot. Each port should match port format
        in tapa graph dict.
        e.g.
        {
            "cat": "istream",
            "name": "a",
            "type": "float",
            "width": 32
        }
    """

    cpp_ports = []
    cpp_pragmas = []
    for port in ports:
        assert isinstance(port, dict)
        assert "cat" in port
        assert "name" in port
        assert "type" in port
        assert "width" in port
        assert port["cat"] in _PORT_TEMPLATE
        port_type = port["type"]
        port_cat = port["cat"]

        # if "name[idx]" exists, replace it with "name_idx"
        name = re.sub(r"\[([^\]]+)\]$", lambda m: f"_{m.group(1)}", port["name"])

        # when port is an array, find array element type
        if port_cat == "scalar":
            match = re.search(r"(?:tapa::)?(\w+)<([^,>]+)", port_type)
            if match:
                port_cat = match.group(1)
                port_type = match.group(2)

        # convert pointer to uint64_t
        if "*" in port_type:
            port_type = "uint64_t"

        cpp_ports.append(
            _PORT_TEMPLATE[port_cat].format(
                name=name,
                type=port_type,
            )
        )
        assert port_cat in _PRAGMA
        cpp_pragmas.append(_PRAGMA[port_cat].format(name=name, type=port_type))
        continue

    # Read template from file
    def_template = Template(_DEF_TEMPLATE_PATH.read_text(encoding="utf-8"))
    decl_template = Template(_DECL_TEMPLATE_PATH.read_text(encoding="utf-8"))

    # Substitute values
    new_def = def_template.substitute(
        name=slot_name,
        ports=", ".join(cpp_ports),
        pragma="\n".join(cpp_pragmas),
    )
    new_decl = decl_template.substitute(
        name=slot_name,
        ports=", ".join(cpp_ports),
    )

    return substitute_top_function(
        top_cpp,
        top_name,
        new_decl,
        new_def,
    )


def substitute_top_function(
    cpp_text: str, top_name: str, new_decl: str, new_def: str
) -> str:
    """
    Replace a top function's declaration and definition in a C++ file.

    Args:
        cpp_file_path: Path to the C++ file
        top_name: Name of the top function to replace
        new_decl: New function declaration (string)
        new_def: New function definition (string)

    Generated by AI
    """

    # Improved pattern for function declaration
    # Matches "void top_name(...);" but not if followed by { (definition)
    decl_pattern = re.compile(
        r"(?P<prefix>\bvoid\s+" + re.escape(top_name) + r"\s*\([^;{]*\)\s*;)",
        re.MULTILINE,
    )

    # Improved pattern for function definition
    # Matches "void top_name(...) {..." and captures everything until the closing brace
    # Uses a balanced brace matcher to handle nested braces
    def_pattern = re.compile(
        r"(?P<prefix>\bvoid\s+"
        + re.escape(top_name)
        + r"\s*\([^{]*\)\s*)\{(?P<body>[^{}]*((\{[^{}]*\})[^{}]*)*)\}",
        re.MULTILINE,
    )

    # Replace declaration (must come before definition replacement)
    new_content, decl_count = decl_pattern.subn(new_decl, cpp_text)
    if decl_count == 0:
        msg = f"Function declaration for {top_name} not found"
        raise ValueError(msg)

    # Replace definition
    def_match = def_pattern.search(new_content)
    if not def_match:
        msg = f"Function definition for {top_name} not found"
        raise ValueError(msg)

    # Preserve indentation of the original opening brace
    indent = (
        def_match.group("prefix")
        .split("\n")[-1]
        .replace(def_match.group("prefix").split("\n")[-1].lstrip(), "")
    )

    # Format the new definition with proper indentation
    new_def_lines = new_def.split("\n")
    formatted_def = new_def_lines[0] + "\n"
    for line in new_def_lines[1:]:
        formatted_def += indent + "    " + line + "\n"
    formatted_def += indent

    return def_pattern.sub(formatted_def, new_content, count=1)
