// ==================================================
// RTL generated by TAPA
//
// Copyright 2025 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
