"""Module header template for TAPAS GraphIR exporter."""

__copyright__ = """
Copyright (c) 2025 RapidStream Design Automation, Inc. and contributors.
All rights reserved. The contributor(s) of this file has/have agreed to the
RapidStream Contributor License Agreement.
"""

from tapa.verilog.graphir_exporter.assets.templates.includes.header_parameters import (
    HEADER_PARAMETERS,
)
from tapa.verilog.graphir_exporter.assets.templates.includes.header_ports import (
    HEADER_PORTS,
)

MODULE_HEADER = f"""
{{% if module.hierarchical_name.is_nonexist() -%}}
/**   Generated by RapidStream   **/
{{# #}}
{{%- elif (not module.hierarchical_name.is_empty())
     and (module.hierarchical_name.__str__() != module.name) -%}}
/**   {{{{ module.hierarchical_name }}}}   **/
{{# #}}
{{%- endif -%}}

module {{{{ module.name -}}}}

{{%- if module.parameters|length > 0 -%}}
{{# #}} #(
{{# #}}    {{# #}}
    {{%- set parameters = module.parameters -%}}
    {{%- filter indent(width=4) -%}}
    {HEADER_PARAMETERS}
    {{%- endfilter -%}}{{# #}}
) {{%- endif -%}}

{{# #}} (
{{%- if module.ports|length > 0 -%}}{{# #}}
    {{# #}}{{%- set ports = module.ports -%}}
    {{%- filter indent(width=4) -%}}
    {HEADER_PORTS}
    {{%- endfilter -%}}{{# #}}
{{# #}}{{%- endif -%}}
);
"""
