{%- if module.hierarchical_name.is_nonexist() -%}
/**   Generated by RapidStream   **/
{# #}
{%- elif (not module.hierarchical_name.is_empty())
     and (module.hierarchical_name.__str__() != module.name) -%}
/**   {{ module.hierarchical_name }}   **/
{# #}
{%- endif -%}

module {{ module.name -}}

{%- if module.parameters|length > 0 -%}
{# #} #(
{# #}    {# #}
    {%- set parameters = module.parameters -%}
    {%- filter indent(width=4) -%}
    {%- include "includes/header-parameters.v" -%}
    {%- endfilter -%}{# #}
) {%- endif -%}

{# #} (
{%- if module.ports|length > 0 -%}{# #}
    {# #}{%- set ports = module.ports -%}
    {%- filter indent(width=4) -%}
    {%- include "includes/header-ports.v" -%}
    {%- endfilter -%}{# #}
{# #}{%- endif -%}
);
