"""Submodules template for TAPAS GraphIR exporter."""

__copyright__ = """
Copyright (c) 2025 RapidStream Design Automation, Inc. and contributors.
All rights reserved. The contributor(s) of this file has/have agreed to the
RapidStream Contributor License Agreement.
"""

from tapa.verilog.graphir_exporter.assets.templates.includes.submodule_connections import (  # noqa: E501
    SUBMODULE_CONNECTIONS,
)
from tapa.verilog.graphir_exporter.assets.templates.includes.submodule_parameters import (  # noqa: E501
    SUBMODULE_PARAMETERS,
)

SUBMODULES = f"""
{{% for submodule in submodules %}}

{{{{ submodule.get_pragma_string() }}}}
{{{{ submodule.module -}}}}

{{%- if submodule.parameters|length > 0 -%}}
{{# #}} #(
    {{%- filter indent(width=4) -%}}
    {SUBMODULE_PARAMETERS}
    {{%- endfilter -%}}
) {{%- endif -%}}

{{# #}} {{{{ submodule.name -}}}}

{{% if submodule.hierarchical_name.is_nonexist() -%}}
{{# #}} /**   Generated by RapidStream   **/
{{%- elif (not submodule.hierarchical_name.is_empty())
     and (submodule.hierarchical_name.__str__() != submodule.name) -%}}
{{# #}} /**   {{{{ submodule.hierarchical_name }}}}   **/
{{%- endif -%}}

{{# #}} (
{{%- if submodule.connections|length > 0 -%}}
    {{%- filter indent(width=4) -%}}
    {SUBMODULE_CONNECTIONS}
    {{%- endfilter -%}}
{{%- endif -%}}
);

{{%- endfor %}}
{{# #}}
"""
