{% for submodule in submodules %}

{{ submodule.get_pragma_string() }}
{{ submodule.module -}}

{%- if submodule.parameters|length > 0 -%}
{# #} #(
    {%- filter indent(width=4) -%}
    {%- include "includes/submodule-parameters.v" -%}
    {%- endfilter -%}
) {%- endif -%}

{# #} {{ submodule.name -}}

{% if submodule.hierarchical_name.is_nonexist() -%}
{# #} /**   Generated by RapidStream   **/
{%- elif (not submodule.hierarchical_name.is_empty())
     and (submodule.hierarchical_name.__str__() != submodule.name) -%}
{# #} /**   {{ submodule.hierarchical_name }}   **/
{%- endif -%}

{# #} (
{%- if submodule.connections|length > 0 -%}
    {%- filter indent(width=4) -%}
    {%- include "includes/submodule-connections.v" -%}
    {%- endfilter -%}
{%- endif -%}
);

{%- endfor %}
{# #}
