name: benchmark

on:
  workflow_dispatch:
    inputs:
      job:
        description: Specifies a single job to run.
        required: false

jobs:
  splag-u280:
    if: github.repository == 'UCLA-VAST/tapa' && (github.event.inputs.job == github.job || github.event.inputs.job == '')

    runs-on:
      - self-hosted
      - Linux
      - xilinx-tools

    strategy:
      matrix:
        xocl-version:
          - 2020.2

    env:
      XILINX_HLS: /opt/tools/xilinx/Vitis_HLS/${{ matrix.xocl-version }}
      XILINX_VITIS: /opt/tools/xilinx/Vitis/${{ matrix.xocl-version }}
      XILINX_VIVADO: /opt/tools/xilinx/Vivado/${{ matrix.xocl-version }}

    steps:
      - name: Checkout myself
        uses: actions/checkout@v1
      - name: Install TAPA
        run: |
          .github/scripts/install-build-deps.sh
          .github/scripts/setup-self-hosted.sh
          python3 -m pip install --editable backend/python
          sudo apt-get install -y --no-install-recommends \
            xilinx-u280-xdma-dev \

          cmake -S . -B build
          cmake --build build --target all --parallel $(nproc)
          cmake --build build --target install
      - name: Checkout benchmark
        run: git clone https://github.com/UCLA-VAST/splag.git
      - name: Configure benchmark
        run: cmake -S splag -B splag/build
      - name: Build benchmark
        run: |
          cmake \
            --build splag/build \
            --target sssp-cosim \
            --target SSSP.xilinx_u280_xdma_201920_3.hw_xclbin \
            --parallel $(nproc)
