name: package

on:
  push:
    tags:
      - "*"

jobs:
  package-deb:
    if: github.repository == 'Blaok/tapa'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
      max-parallel: 1

    steps:
      - name: Checkout myself
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get purge -y libgcc-*-dev || true
          ./.github/scripts/install-build-deps.sh
          ./.github/scripts/setup-github-hosted.sh
      - name: Configure myself
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Cache llvm-src
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-src
          key: ${{ matrix.os }}-llvm-src-202204-1
      - name: Cache llvm-build
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-build
          key: ${{ matrix.os }}-llvm-build-202204-1
      - name: Cache llvm-subbuild
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-subbuild
          key: ${{ matrix.os }}-llvm-subbuild-202204-1
      - name: Package myself
        run: cmake --build build --target package
      - name: Cache APT database
        uses: actions/cache@v1
        with:
          path: apt-db-cache
          key: ${{ runner.os }}-apt-db-cache
      - name: Update APT repository
        run: ./.github/scripts/upload-apt-repo.sh
        env:
          BUILD_DIR: build
          CACHE_DIR: apt-db-cache
          LABEL: Extending High-Level Synthesis for Task-Parallel Programs
          GPG_KEY: ${{ secrets.GPG_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

  package-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install build
        run: pip install --upgrade build
      - name: Checkout myself
        uses: actions/checkout@v2
      - name: Build myself
        run: python -m build backend/python
      - name: Publish to PyPI
        if: github.repository == 'Blaok/tapa'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: backend/python/dist/
